name: Nathan Penn General Studio Photographer
copyright: Nathan Penn Photography
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
sass:
    style: compressed
exclude: [
  "test",
  "npm-debug.log",
  "package.json",
  "pre-test-component-builder.js",
  "README.md",
  "rollup.config.js",
  "rollup.test.config.js"
]
data_dir: data
